##########################################################################
# This is a wrapper function that relies on the read_phd script available
# from PicoQuant to load and parse a .phd file (originally generated by the
# PicoHarp.)  The File is designated by (FileName) and must be located in 
# the current directory.

# The function outputs a data Object (Data) with a few commonly-used
# parameters. Specifically:

# Data.NumCurves --> The number of unique traces in the file

# Data.Data --> A {NumCurves}(65536x2) cell array containing the
# binned/histogrammed count data from the detector, along with the compued
# time axis

# Data.StartRate --> A 1xNumCurves vector containing the start rates (i.e. trigger rate on Channel 0) for each curve
# Data.StopRate --> A 1xNumCurves vector containing the stop rates (i.e. count rate on Channel 0) for each curve
# Data.TimeStep --> A 1xNumCurves vector containing the temporal widths of the histogram bins for each curve
# Data.Peak --> A 1xNumCurves vector containing the peak number of counts histogram of each curve

# Modifications to the code to give this functionality are marked by
# #MWBW... except for commenting out the comedic number of fprintf
# statements in the original script. I assume that you can just figure this
# out for yourself! :-)

###########################################################################

##### Legacy comments from the PicoQuant Script

# PicoHarp 300    File Access Demo in Matlab

# This script reads a binary PicoHarp 300 data file (*.phd)
# and displays its contents. Works with file format version 2.0 only!

# Tested with Matlab 6.
# Peter Kapusta, PicoQuant GmbH, September 2006
# This is demo code. Use at your own risk. No warranties.
# Make sure you have enough memory when loading large files!

##### #MWBW

# clear all;
# clc;
# 
# [filename, pathname]=uigetfile('*.phd', 'Interactive mode data:', 0, 0);
# fid=fopen([pathname filename]);





def Data(FileName):
	fid=open('FileName', 'r')
	print '=====================================================,\n'
	print 'Loading:', FileName
	print '=====================================================,\n'
	
	
	